/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pair client and issue auth cookie
         * @description Pairing endpoint for auth-required mode.
         *     Accepts token via query (`?token=...`) and issues the pairing cookie when valid.
         */
        get: operations["getPair"];
        put?: never;
        /** Pair client and issue auth cookie */
        post: operations["postPair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API and app version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server capability list */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request graceful runtime restart (local-first, LAN opt-in) */
        post: operations["postControlRestart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request graceful runtime stop */
        post: operations["postControlStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get control-plane runtime status and telemetry */
        get: operations["getControlStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get control-plane settings */
        get: operations["getControlSettings"];
        put?: never;
        /** Apply control-plane settings */
        post: operations["postControlSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pair control-plane session and issue admin cookie */
        get: operations["getControlPair"];
        put?: never;
        /** Pair control-plane session and issue admin cookie */
        post: operations["postControlPair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available presets */
        get: operations["getPresets"];
        put?: never;
        /** Replace preset catalog */
        post: operations["postPresets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get library sources with global enabled states */
        get: operations["getSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{sourceId}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update global enabled state for a source */
        post: operations["postSourceEnabled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match filter state to preset */
        post: operations["postPresetMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a random media item */
        post: operations["postRandom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update favorite state for an item */
        post: operations["postFavorite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blacklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update blacklist state for an item */
        post: operations["postBlacklist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/record-playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record playback for an item */
        post: operations["postRecordPlayback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch authoritative item state snapshots
         * @description Re-fetch endpoint used during SSE reconnect/resync flows.
         *     Clients submit known item paths and receive current favorite/blacklist
         *     state with the latest revision observed for each item.
         */
        post: operations["postLibraryStates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get tag editor model snapshot */
        post: operations["postTagEditorModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/apply-item-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply batch add/remove tag deltas to items */
        post: operations["postTagEditorApplyItemTags"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/upsert-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update category metadata */
        post: operations["postTagEditorUpsertCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/upsert-tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update tag metadata */
        post: operations["postTagEditorUpsertTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/rename-tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename tag and optionally move category */
        post: operations["postTagEditorRenameTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/delete-tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a tag */
        post: operations["postTagEditorDeleteTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/delete-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a category and optionally reassign tags */
        post: operations["postTagEditorDeleteCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/sync-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace server tag catalog snapshot from client source-of-truth */
        post: operations["postTagEditorSyncCatalog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/sync-item-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hydrate item-tag snapshots for requested items */
        post: operations["postTagEditorSyncItemTags"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start unified refresh run */
        post: operations["postRefreshStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get refresh status snapshot */
        get: operations["getRefreshStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get core-owned refresh settings */
        get: operations["getRefreshSettings"];
        put?: never;
        /** Update core-owned refresh settings */
        post: operations["postRefreshSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get generated thumbnail by item id */
        get: operations["getThumbnailByItemId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream server events
         * @description SSE stream with monotonic `id` values matching envelope `revision`.
         *     Reconnect behavior:
         *     - Client reconnects with `Last-Event-ID`.
         *     - Server replays buffered events newer than that revision when available.
         *     - If the revision gap exceeds replay buffer retention, server emits a
         *       `resyncRequired` event and client must call `/api/library-states`.
         */
        get: operations["getEventsSse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        PairRequest: {
            token?: string | null;
        };
        PairResponse: {
            paired: boolean;
            message: string;
        };
        ErrorResponse: {
            error: string;
        };
        VersionResponse: {
            appVersion: string;
            apiVersion: string;
            assetsVersion?: string | null;
            minimumCompatibleApiVersion: string;
            supportedApiVersions: string[];
            capabilities: string[];
        };
        CapabilitiesResponse: {
            capabilities: string[];
        };
        RestartResponse: {
            accepted: boolean;
            message: string;
        };
        ControlRuntimeSettingsSnapshot: {
            /** @enum {string} */
            adminAuthMode: "Off" | "TokenRequired";
            adminSharedToken?: string | null;
        };
        ControlApplyResult: {
            accepted: boolean;
            restartRequired: boolean;
            message: string;
            errors?: string[];
        };
        ControlSettingsApplyResponse: {
            settings: components["schemas"]["ControlRuntimeSettingsSnapshot"];
            result: components["schemas"]["ControlApplyResult"];
        };
        ApiEventTelemetryEntry: {
            /** Format: date-time */
            timestampUtc: string;
            direction: string;
            method: string;
            path: string;
            /** Format: int32 */
            statusCode?: number | null;
            eventType?: string | null;
        };
        ConnectedClientsSnapshot: {
            /** Format: int32 */
            apiPairedSessions: number;
            /** Format: int32 */
            controlPairedSessions: number;
            /** Format: int32 */
            sseSubscribers: number;
        };
        ControlStatusResponse: {
            /** Format: date-time */
            serverTimeUtc: string;
            isHealthy: boolean;
            listenUrl: string;
            lanExposed: boolean;
            connectedClients: components["schemas"]["ConnectedClientsSnapshot"];
            incomingApiEvents?: components["schemas"]["ApiEventTelemetryEntry"][];
            outgoingApiEvents?: components["schemas"]["ApiEventTelemetryEntry"][];
        };
        PresetResponse: {
            id: string;
            name: string;
            summary?: string | null;
            filterState?: {
                [key: string]: unknown;
            } | null;
        };
        SourceResponse: {
            id: string;
            rootPath: string;
            displayName?: string | null;
            isEnabled: boolean;
        };
        UpdateSourceEnabledRequest: {
            isEnabled: boolean;
        };
        RandomRequest: {
            presetId?: string;
            filterState?: {
                [key: string]: unknown;
            } | null;
            clientId?: string | null;
            /** @default true */
            includeVideos: boolean;
            /** @default true */
            includePhotos: boolean;
            randomizationMode?: string | null;
        };
        RandomResponse: {
            id: string;
            displayName: string;
            /** @enum {string} */
            mediaType: "video" | "photo";
            /** Format: double */
            durationSeconds?: number | null;
            mediaUrl: string;
            isFavorite: boolean;
            isBlacklisted: boolean;
        };
        PresetMatchRequest: {
            filterState?: {
                [key: string]: unknown;
            } | null;
        };
        PresetMatchResponse: {
            matched: boolean;
            presetId?: string | null;
            presetName?: string | null;
        };
        FavoriteRequest: {
            path: string;
            isFavorite: boolean;
        };
        BlacklistRequest: {
            path: string;
            isBlacklisted: boolean;
        };
        RecordPlaybackRequest: {
            clientId?: string | null;
            path: string;
        };
        ServerEventEnvelope: {
            /** Format: int64 */
            revision: number;
            eventType: string;
            /** Format: date-time */
            timestamp: string;
            payload: components["schemas"]["ItemStateChangedPayload"] | components["schemas"]["PlaybackRecordedPayload"] | components["schemas"]["ResyncRequiredPayload"] | components["schemas"]["ItemTagsChangedPayload"] | components["schemas"]["TagCatalogChangedPayload"] | components["schemas"]["SourceStateChangedPayload"] | components["schemas"]["RefreshStatusChangedPayload"];
        };
        ItemStateChangedPayload: {
            itemId: string;
            path: string;
            isFavorite: boolean;
            isBlacklisted: boolean;
        };
        PlaybackRecordedPayload: {
            path: string;
            clientId?: string | null;
        };
        ResyncRequiredPayload: {
            /** @example revisionGap */
            reason: string;
            /** Format: int64 */
            lastEventId: number;
            /** Format: int64 */
            currentRevision: number;
        };
        LibraryStatesRequest: {
            paths?: string[] | null;
        };
        LibraryStateResponse: {
            itemId: string;
            path: string;
            isFavorite: boolean;
            isBlacklisted: boolean;
            /** Format: int64 */
            revision: number;
        };
        FilterPresetSnapshot: {
            name: string;
            filterState: {
                [key: string]: unknown;
            };
        };
        TagCategorySnapshot: {
            id: string;
            name: string;
            /** Format: int32 */
            sortOrder: number;
        };
        TagSnapshot: {
            name: string;
            categoryId: string;
        };
        ItemTagsSnapshot: {
            itemId: string;
            tags: string[];
        };
        TagEditorModelRequest: {
            itemIds?: string[];
        };
        TagEditorModelResponse: {
            categories: components["schemas"]["TagCategorySnapshot"][];
            tags: components["schemas"]["TagSnapshot"][];
            items: components["schemas"]["ItemTagsSnapshot"][];
        };
        ApplyItemTagsRequest: {
            itemIds: string[];
            addTags?: string[];
            removeTags?: string[];
        };
        UpsertCategoryRequest: {
            id: string;
            name: string;
            /** Format: int32 */
            sortOrder?: number | null;
        };
        UpsertTagRequest: {
            name: string;
            categoryId?: string;
        };
        RenameTagRequest: {
            oldName: string;
            newName: string;
            newCategoryId?: string | null;
        };
        DeleteTagRequest: {
            name: string;
        };
        DeleteCategoryRequest: {
            categoryId: string;
            newCategoryId?: string | null;
        };
        SyncTagCatalogRequest: {
            categories: components["schemas"]["TagCategorySnapshot"][];
            tags: components["schemas"]["TagSnapshot"][];
        };
        SyncItemTagsRequest: {
            items: components["schemas"]["ItemTagsSnapshot"][];
        };
        RefreshStartRequest: {
            trigger?: string;
        };
        RefreshStartResponse: {
            accepted: boolean;
            message?: string | null;
            runId?: string | null;
        };
        RefreshSettingsSnapshot: {
            autoRefreshEnabled: boolean;
            /** Format: int32 */
            autoRefreshIntervalMinutes: number;
        };
        RefreshStageProgress: {
            stage: string;
            /** Format: int32 */
            percent: number;
            message: string;
            isComplete: boolean;
        };
        RefreshStatusSnapshot: {
            isRunning: boolean;
            runId?: string | null;
            trigger: string;
            /** Format: date-time */
            startedUtc?: string | null;
            /** Format: date-time */
            completedUtc?: string | null;
            currentStage?: string | null;
            lastError?: string | null;
            stages: components["schemas"]["RefreshStageProgress"][];
        };
        ItemTagsChangedPayload: {
            itemIds: string[];
            addedTags: string[];
            removedTags: string[];
        };
        TagCatalogChangedPayload: {
            reason: string;
            categories: components["schemas"]["TagCategorySnapshot"][];
            tags: components["schemas"]["TagSnapshot"][];
        };
        SourceStateChangedPayload: {
            sourceId: string;
            isEnabled: boolean;
        };
        RefreshStatusChangedPayload: {
            snapshot: components["schemas"]["RefreshStatusSnapshot"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getPair: {
        parameters: {
            query?: {
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pairing succeeded or auth disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postPair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Pairing succeeded or auth disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Unauthorized when auth is required and localhost trust is disabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
            /** @description Unauthorized when auth is required and localhost trust is disabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postControlRestart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restart accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Restart already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
        };
    };
    postControlStop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stop accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Lifecycle operation already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
        };
    };
    getControlStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control status snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlStatusResponse"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getControlSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlRuntimeSettingsSnapshot"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postControlSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlRuntimeSettingsSnapshot"];
            };
        };
        responses: {
            /** @description Settings apply result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlSettingsApplyResponse"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getControlPair: {
        parameters: {
            query?: {
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control pairing succeeded or admin auth disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Control LAN access disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postControlPair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Control pairing succeeded or admin auth disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Control LAN access disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preset list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"][];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilterPresetSnapshot"][];
            };
        };
        responses: {
            /** @description Preset catalog updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postSourceEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSourceEnabledRequest"];
            };
        };
        responses: {
            /** @description Source state updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postPresetMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetMatchRequest"];
            };
        };
        responses: {
            /** @description Preset match result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetMatchResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postRandom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RandomRequest"];
            };
        };
        responses: {
            /** @description Random media result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RandomResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoriteRequest"];
            };
        };
        responses: {
            /** @description Favorite updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postBlacklist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlacklistRequest"];
            };
        };
        responses: {
            /** @description Blacklist updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postRecordPlayback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPlaybackRequest"];
            };
        };
        responses: {
            /** @description Playback recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postLibraryStates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryStatesRequest"];
            };
        };
        responses: {
            /** @description State snapshots for requested paths (or all known states when no paths are provided) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryStateResponse"][];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagEditorModelRequest"];
            };
        };
        responses: {
            /** @description Tag editor model snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagEditorModelResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorApplyItemTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyItemTagsRequest"];
            };
        };
        responses: {
            /** @description Tag delta applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorUpsertCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCategoryRequest"];
            };
        };
        responses: {
            /** @description Category upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorUpsertTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertTagRequest"];
            };
        };
        responses: {
            /** @description Tag upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorRenameTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameTagRequest"];
            };
        };
        responses: {
            /** @description Tag renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorDeleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteTagRequest"];
            };
        };
        responses: {
            /** @description Tag deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorDeleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteCategoryRequest"];
            };
        };
        responses: {
            /** @description Category deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorSyncCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncTagCatalogRequest"];
            };
        };
        responses: {
            /** @description Catalog synchronized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorSyncItemTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncItemTagsRequest"];
            };
        };
        responses: {
            /** @description Item tags synchronized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postRefreshStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshStartRequest"];
            };
        };
        responses: {
            /** @description Refresh run accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshStartResponse"];
                };
            };
            /** @description Refresh already running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRefreshStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current refresh status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshStatusSnapshot"];
                };
            };
        };
    };
    getRefreshSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshSettingsSnapshot"];
                };
            };
        };
    };
    postRefreshSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshSettingsSnapshot"];
            };
        };
        responses: {
            /** @description Updated refresh settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshSettingsSnapshot"];
                };
            };
        };
    };
    getThumbnailByItemId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thumbnail image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description Thumbnail not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEventsSse: {
        parameters: {
            query?: {
                /** @description Query-string reconnect revision fallback for browser EventSource clients. */
                lastEventId?: string;
            };
            header?: {
                /** @description Last acknowledged SSE revision from the previous connection. */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream (SSE) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ServerEventEnvelope"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
