/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pair client and issue auth cookie
         * @description Pairing endpoint for auth-required mode.
         *     Accepts token via query (`?token=...`) and issues the pairing cookie when valid.
         */
        get: operations["getPair"];
        put?: never;
        /** Pair client and issue auth cookie */
        post: operations["postPair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API and app version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server capability list */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request graceful runtime restart (local-first, LAN opt-in) */
        post: operations["postControlRestart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request graceful runtime stop */
        post: operations["postControlStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get control-plane runtime status and telemetry */
        get: operations["getControlStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get control-plane settings */
        get: operations["getControlSettings"];
        put?: never;
        /** Apply control-plane settings */
        post: operations["postControlSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/logs/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read server last.log lines */
        get: operations["getControlServerLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/testing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current operator testing mode and fault flags */
        get: operations["getControlTestingState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/testing/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update testing mode and operator fault simulation flags */
        post: operations["postControlTestingUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/testing/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset all testing scenario flags while preserving testing mode state */
        post: operations["postControlTestingReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pair control-plane session and issue admin cookie */
        get: operations["getControlPair"];
        put?: never;
        /** Pair control-plane session and issue admin cookie */
        post: operations["postControlPair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available presets */
        get: operations["getPresets"];
        put?: never;
        /** Replace preset catalog */
        post: operations["postPresets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get library sources with global enabled states */
        get: operations["getSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a media source folder into library.json */
        post: operations["postSourceImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current library projection snapshot */
        get: operations["getLibraryProjection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{sourceId}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update global enabled state for a source */
        post: operations["postSourceEnabled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match filter state to preset */
        post: operations["postPresetMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a random media item */
        post: operations["postRandom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{idOrToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream media by stable item id or issued playback token */
        get: operations["getMediaByIdOrToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update favorite state for an item */
        post: operations["postFavorite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blacklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update blacklist state for an item */
        post: operations["postBlacklist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/record-playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record playback for an item */
        post: operations["postRecordPlayback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playback/clear-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear playback stats */
        post: operations["postClearPlaybackStats"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch authoritative item state snapshots
         * @description Re-fetch endpoint used during SSE reconnect/resync flows.
         *     Clients submit known item paths and receive current favorite/blacklist
         *     state with the latest revision observed for each item.
         */
        post: operations["postLibraryStates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get tag editor model snapshot */
        post: operations["postTagEditorModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/apply-item-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply batch add/remove tag deltas to items */
        post: operations["postTagEditorApplyItemTags"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/upsert-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update category metadata */
        post: operations["postTagEditorUpsertCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/upsert-tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update tag metadata */
        post: operations["postTagEditorUpsertTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/rename-tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename tag and optionally move category */
        post: operations["postTagEditorRenameTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/delete-tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a tag */
        post: operations["postTagEditorDeleteTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/delete-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a category and optionally reassign tags */
        post: operations["postTagEditorDeleteCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/sync-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace server tag catalog snapshot from client source-of-truth */
        post: operations["postTagEditorSyncCatalog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag-editor/sync-item-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hydrate item-tag snapshots for requested items */
        post: operations["postTagEditorSyncItemTags"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start unified refresh run */
        post: operations["postRefreshStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get refresh status snapshot */
        get: operations["getRefreshStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get core-owned refresh settings */
        get: operations["getRefreshSettings"];
        put?: never;
        /** Update core-owned refresh settings */
        post: operations["postRefreshSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/duplicates/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan for fingerprint-based duplicate groups */
        post: operations["postDuplicateScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/duplicates/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply duplicate keep/delete selections */
        post: operations["postDuplicateApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/autotag/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan for auto-tag suggestions */
        post: operations["postAutoTagScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/autotag/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply auto-tag assignments */
        post: operations["postAutoTagApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest client-originated log events to centralized server log */
        post: operations["postClientLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get generated thumbnail by item id */
        get: operations["getThumbnailByItemId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream server events
         * @description SSE stream with monotonic `id` values matching envelope `revision`.
         *     Reconnect behavior:
         *     - Client reconnects with `Last-Event-ID`.
         *     - Server replays buffered events newer than that revision when available.
         *     - If the revision gap exceeds replay buffer retention, server emits a
         *       `resyncRequired` event and client must call `/api/library-states`.
         *     Identity/session continuity:
         *     - Clients should provide a stable `clientId` per installation/device.
         *     - Clients may provide an optional `sessionId` per runtime session to
         *       correlate reconnect attempts and playback-originated events.
         */
        get: operations["getEventsSse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        PairRequest: {
            token?: string | null;
        };
        PairResponse: {
            paired: boolean;
            message: string;
        };
        ErrorResponse: {
            error: string;
        };
        VersionResponse: {
            appVersion: string;
            apiVersion: string;
            assetsVersion?: string | null;
            minimumCompatibleApiVersion: string;
            supportedApiVersions: string[];
            capabilities: string[];
        };
        CapabilitiesResponse: {
            capabilities: string[];
        };
        RestartResponse: {
            accepted: boolean;
            message: string;
        };
        ControlRuntimeSettingsSnapshot: {
            /** @enum {string} */
            adminAuthMode: "Off" | "TokenRequired";
            adminSharedToken?: string | null;
        };
        ControlApplyResult: {
            accepted: boolean;
            restartRequired: boolean;
            message: string;
            errors?: string[];
        };
        ControlSettingsApplyResponse: {
            settings: components["schemas"]["ControlRuntimeSettingsSnapshot"];
            result: components["schemas"]["ControlApplyResult"];
        };
        ApiEventTelemetryEntry: {
            /** Format: date-time */
            timestampUtc: string;
            direction: string;
            method: string;
            path: string;
            /** Format: int32 */
            statusCode?: number | null;
            eventType?: string | null;
        };
        ConnectedClientsSnapshot: {
            /** Format: int32 */
            apiPairedSessions: number;
            /** Format: int32 */
            controlPairedSessions: number;
            /** Format: int32 */
            sseSubscribers: number;
            apiSessions: components["schemas"]["SessionInfoSnapshot"][];
            controlSessions: components["schemas"]["SessionInfoSnapshot"][];
            activeSseClients: components["schemas"]["SseClientInfoSnapshot"][];
        };
        ControlStatusResponse: {
            /** Format: date-time */
            serverTimeUtc: string;
            isHealthy: boolean;
            listenUrl: string;
            lanExposed: boolean;
            connectedClients: components["schemas"]["ConnectedClientsSnapshot"];
            incomingApiEvents?: components["schemas"]["ApiEventTelemetryEntry"][];
            outgoingApiEvents?: components["schemas"]["ApiEventTelemetryEntry"][];
            testing?: components["schemas"]["OperatorTestingStateSnapshot"];
        };
        SessionInfoSnapshot: {
            sessionId: string;
            /** Format: date-time */
            createdUtc: string;
            /** Format: date-time */
            lastSeenUtc: string;
            /** Format: date-time */
            expiresUtc: string;
        };
        SseClientInfoSnapshot: {
            connectionId: string;
            clientId?: string | null;
            sessionId?: string | null;
            clientType?: string | null;
            deviceName?: string | null;
            userAgent?: string | null;
            /** Format: date-time */
            connectedUtc: string;
            remoteAddress?: string | null;
        };
        ServerLogResponse: {
            sourcePath: string;
            /** Format: int32 */
            totalLinesRead: number;
            lines: string[];
        };
        OperatorTestingStateSnapshot: {
            testingModeEnabled: boolean;
            forceApiVersionMismatch: boolean;
            forceCapabilityMismatch: boolean;
            forceApiUnavailable: boolean;
            forceMediaMissing: boolean;
            forceSseDisconnect: boolean;
            /** Format: date-time */
            lastUpdatedUtc: string;
        };
        OperatorTestingUpdateRequest: {
            testingModeEnabled?: boolean | null;
            forceApiVersionMismatch?: boolean | null;
            forceCapabilityMismatch?: boolean | null;
            forceApiUnavailable?: boolean | null;
            forceMediaMissing?: boolean | null;
            forceSseDisconnect?: boolean | null;
        };
        OperatorTestingActionResponse: {
            accepted: boolean;
            message: string;
            state: components["schemas"]["OperatorTestingStateSnapshot"];
        };
        PresetResponse: {
            id: string;
            name: string;
            summary?: string | null;
            filterState?: {
                [key: string]: unknown;
            } | null;
        };
        SourceResponse: {
            id: string;
            rootPath: string;
            displayName?: string | null;
            isEnabled: boolean;
        };
        UpdateSourceEnabledRequest: {
            isEnabled: boolean;
        };
        SourceImportRequest: {
            rootPath: string;
            displayName?: string | null;
        };
        SourceImportResponse: {
            accepted: boolean;
            message: string;
            sourceId?: string | null;
            /** Format: int32 */
            importedCount: number;
            /** Format: int32 */
            updatedCount: number;
        };
        LibraryProjectionResponse: {
            [key: string]: unknown;
        };
        RandomRequest: {
            presetId?: string;
            filterState?: {
                [key: string]: unknown;
            } | null;
            clientId?: string | null;
            sessionId?: string | null;
            /** @default true */
            includeVideos: boolean;
            /** @default true */
            includePhotos: boolean;
            randomizationMode?: string | null;
        };
        RandomResponse: {
            id: string;
            displayName: string;
            /** @enum {string} */
            mediaType: "video" | "photo";
            /** Format: double */
            durationSeconds?: number | null;
            mediaUrl: string;
            isFavorite: boolean;
            isBlacklisted: boolean;
        };
        PresetMatchRequest: {
            filterState?: {
                [key: string]: unknown;
            } | null;
        };
        PresetMatchResponse: {
            matched: boolean;
            presetId?: string | null;
            presetName?: string | null;
        };
        FavoriteRequest: {
            path: string;
            isFavorite: boolean;
        };
        BlacklistRequest: {
            path: string;
            isBlacklisted: boolean;
        };
        RecordPlaybackRequest: {
            clientId?: string | null;
            sessionId?: string | null;
            path: string;
        };
        ClearPlaybackStatsRequest: {
            itemPaths?: string[] | null;
        };
        ClearPlaybackStatsResponse: {
            /** Format: int32 */
            clearedCount: number;
        };
        ServerEventEnvelope: {
            /** Format: int64 */
            revision: number;
            eventType: string;
            /** Format: date-time */
            timestamp: string;
            payload: components["schemas"]["ItemStateChangedPayload"] | components["schemas"]["PlaybackRecordedPayload"] | components["schemas"]["ResyncRequiredPayload"] | components["schemas"]["ItemTagsChangedPayload"] | components["schemas"]["TagCatalogChangedPayload"] | components["schemas"]["SourceStateChangedPayload"] | components["schemas"]["RefreshStatusChangedPayload"];
        };
        ItemStateChangedPayload: {
            itemId: string;
            path: string;
            isFavorite: boolean;
            isBlacklisted: boolean;
        };
        PlaybackRecordedPayload: {
            path: string;
            clientId?: string | null;
            sessionId?: string | null;
        };
        ResyncRequiredPayload: {
            /** @example revisionGap */
            reason: string;
            /** Format: int64 */
            lastEventId: number;
            /** Format: int64 */
            currentRevision: number;
        };
        LibraryStatesRequest: {
            clientId?: string | null;
            sessionId?: string | null;
            paths?: string[] | null;
        };
        LibraryStateResponse: {
            itemId: string;
            path: string;
            isFavorite: boolean;
            isBlacklisted: boolean;
            /** Format: int64 */
            revision: number;
        };
        FilterPresetSnapshot: {
            name: string;
            filterState: {
                [key: string]: unknown;
            };
        };
        TagCategorySnapshot: {
            id: string;
            name: string;
            /** Format: int32 */
            sortOrder: number;
        };
        TagSnapshot: {
            name: string;
            categoryId: string;
        };
        ItemTagsSnapshot: {
            itemId: string;
            tags: string[];
        };
        TagEditorModelRequest: {
            itemIds?: string[];
        };
        TagEditorModelResponse: {
            categories: components["schemas"]["TagCategorySnapshot"][];
            tags: components["schemas"]["TagSnapshot"][];
            items: components["schemas"]["ItemTagsSnapshot"][];
        };
        ApplyItemTagsRequest: {
            itemIds: string[];
            addTags?: string[];
            removeTags?: string[];
        };
        UpsertCategoryRequest: {
            id: string;
            name: string;
            /** Format: int32 */
            sortOrder?: number | null;
        };
        UpsertTagRequest: {
            name: string;
            categoryId?: string;
        };
        RenameTagRequest: {
            oldName: string;
            newName: string;
            newCategoryId?: string | null;
        };
        DeleteTagRequest: {
            name: string;
        };
        DeleteCategoryRequest: {
            categoryId: string;
            newCategoryId?: string | null;
        };
        SyncTagCatalogRequest: {
            categories: components["schemas"]["TagCategorySnapshot"][];
            tags: components["schemas"]["TagSnapshot"][];
        };
        SyncItemTagsRequest: {
            items: components["schemas"]["ItemTagsSnapshot"][];
        };
        RefreshStartRequest: {
            trigger?: string;
        };
        RefreshStartResponse: {
            accepted: boolean;
            message?: string | null;
            runId?: string | null;
        };
        RefreshSettingsSnapshot: {
            autoRefreshEnabled: boolean;
            /** Format: int32 */
            autoRefreshIntervalMinutes: number;
            /**
             * Format: int32
             * @description Max parallel fingerprint hashes during core refresh (1-16).
             */
            fingerprintScanMaxDegreeOfParallelism?: number;
        };
        DuplicateScanRequest: {
            /** @enum {string} */
            scope?: "CurrentSource" | "AllEnabledSources" | "AllSources";
            sourceId?: string | null;
        };
        DuplicateScanResponse: {
            groups: components["schemas"]["DuplicateGroupResponse"][];
            /** Format: int32 */
            excludedPending: number;
            /** Format: int32 */
            excludedFailed: number;
            /** Format: int32 */
            excludedStale: number;
        };
        DuplicateGroupResponse: {
            fingerprint: string;
            items: components["schemas"]["DuplicateGroupItemResponse"][];
        };
        DuplicateGroupItemResponse: {
            itemId: string;
            fullPath: string;
            sourceId: string;
            isFavorite: boolean;
            isBlacklisted: boolean;
            /** Format: int32 */
            playCount: number;
            /** Format: int32 */
            tagCount: number;
        };
        DuplicateApplyRequest: {
            selections: components["schemas"]["DuplicateApplySelection"][];
        };
        DuplicateApplySelection: {
            keepItemId: string;
            itemIds: string[];
        };
        DuplicateApplyResponse: {
            /** Format: int32 */
            deletedOnDisk: number;
            /** Format: int32 */
            removedFromLibrary: number;
            failures: components["schemas"]["DuplicateApplyFailure"][];
        };
        DuplicateApplyFailure: {
            fullPath: string;
            reason: string;
        };
        AutoTagScanRequest: {
            scanFullLibrary?: boolean;
            itemIds?: string[];
        };
        AutoTagScanResponse: {
            rows: components["schemas"]["AutoTagMatchRowResponse"][];
        };
        AutoTagMatchRowResponse: {
            tagName: string;
            /** Format: int32 */
            totalMatchedCount: number;
            /** Format: int32 */
            wouldChangeCount: number;
            files: components["schemas"]["AutoTagMatchedFileResponse"][];
        };
        AutoTagMatchedFileResponse: {
            fullPath: string;
            displayPath: string;
            needsChange: boolean;
        };
        AutoTagApplyRequest: {
            assignments: components["schemas"]["AutoTagAssignment"][];
        };
        AutoTagAssignment: {
            tagName: string;
            itemPaths: string[];
        };
        AutoTagApplyResponse: {
            /** Format: int32 */
            assignmentsAdded: number;
            changedItemPaths: string[];
        };
        ClientLogRequest: {
            source: string;
            level: string;
            message: string;
        };
        RefreshStageProgress: {
            stage: string;
            /** Format: int32 */
            percent: number;
            message: string;
            isComplete: boolean;
        };
        RefreshStatusSnapshot: {
            isRunning: boolean;
            runId?: string | null;
            trigger: string;
            /** Format: date-time */
            startedUtc?: string | null;
            /** Format: date-time */
            completedUtc?: string | null;
            currentStage?: string | null;
            lastError?: string | null;
            stages: components["schemas"]["RefreshStageProgress"][];
        };
        ItemTagsChangedPayload: {
            itemIds: string[];
            addedTags: string[];
            removedTags: string[];
        };
        TagCatalogChangedPayload: {
            reason: string;
            categories: components["schemas"]["TagCategorySnapshot"][];
            tags: components["schemas"]["TagSnapshot"][];
        };
        SourceStateChangedPayload: {
            sourceId: string;
            isEnabled: boolean;
        };
        RefreshStatusChangedPayload: {
            snapshot: components["schemas"]["RefreshStatusSnapshot"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getPair: {
        parameters: {
            query?: {
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pairing succeeded or auth disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postPair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Pairing succeeded or auth disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Unauthorized when auth is required and localhost trust is disabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
            /** @description Unauthorized when auth is required and localhost trust is disabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postControlRestart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restart accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Restart already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
        };
    };
    postControlStop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stop accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Lifecycle operation already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
        };
    };
    getControlStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control status snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlStatusResponse"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getControlSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlRuntimeSettingsSnapshot"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postControlSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlRuntimeSettingsSnapshot"];
            };
        };
        responses: {
            /** @description Settings apply result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlSettingsApplyResponse"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getControlServerLogs: {
        parameters: {
            query?: {
                /** @description Number of trailing lines to return. */
                tail?: number;
                /** @description Optional case-insensitive contains filter. */
                contains?: string | null;
                /** @description Optional level hint filter (for example info/warn/error). */
                level?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log snapshot response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerLogResponse"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getControlTestingState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operator testing state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorTestingStateSnapshot"];
                };
            };
            /** @description Unauthorized when control admin auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postControlTestingUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorTestingUpdateRequest"];
            };
        };
        responses: {
            /** @description Testing state update result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorTestingActionResponse"];
                };
            };
            /** @description Unauthorized for testing actions while control admin auth is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Testing mode is required before enabling fault simulation flags */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postControlTestingReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Testing reset result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorTestingActionResponse"];
                };
            };
            /** @description Unauthorized for testing actions while control admin auth is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden when request is non-local and LAN control access is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getControlPair: {
        parameters: {
            query?: {
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control pairing succeeded or admin auth disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Control LAN access disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postControlPair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Control pairing succeeded or admin auth disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Control LAN access disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preset list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"][];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No playable media available for current request or testing scenario */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilterPresetSnapshot"][];
            };
        };
        responses: {
            /** @description Preset catalog updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postSourceImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceImportRequest"];
            };
        };
        responses: {
            /** @description Source import completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportResponse"];
                };
            };
            /** @description Invalid import request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLibraryProjection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library projection JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryProjectionResponse"];
                };
            };
        };
    };
    postSourceEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSourceEnabledRequest"];
            };
        };
        responses: {
            /** @description Source state updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postPresetMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetMatchRequest"];
            };
        };
        responses: {
            /** @description Preset match result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetMatchResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postRandom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RandomRequest"];
            };
        };
        responses: {
            /** @description Random media result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RandomResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMediaByIdOrToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media stream response with range support */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoriteRequest"];
            };
        };
        responses: {
            /** @description Favorite updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postBlacklist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlacklistRequest"];
            };
        };
        responses: {
            /** @description Blacklist updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postRecordPlayback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPlaybackRequest"];
            };
        };
        responses: {
            /** @description Playback recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postClearPlaybackStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClearPlaybackStatsRequest"];
            };
        };
        responses: {
            /** @description Playback stats cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearPlaybackStatsResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postLibraryStates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryStatesRequest"];
            };
        };
        responses: {
            /** @description State snapshots for requested paths (or all known states when no paths are provided) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryStateResponse"][];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagEditorModelRequest"];
            };
        };
        responses: {
            /** @description Tag editor model snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagEditorModelResponse"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorApplyItemTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyItemTagsRequest"];
            };
        };
        responses: {
            /** @description Tag delta applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorUpsertCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCategoryRequest"];
            };
        };
        responses: {
            /** @description Category upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorUpsertTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertTagRequest"];
            };
        };
        responses: {
            /** @description Tag upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorRenameTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameTagRequest"];
            };
        };
        responses: {
            /** @description Tag renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorDeleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteTagRequest"];
            };
        };
        responses: {
            /** @description Tag deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorDeleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteCategoryRequest"];
            };
        };
        responses: {
            /** @description Category deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorSyncCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncTagCatalogRequest"];
            };
        };
        responses: {
            /** @description Catalog synchronized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postTagEditorSyncItemTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncItemTagsRequest"];
            };
        };
        responses: {
            /** @description Item tags synchronized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postRefreshStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshStartRequest"];
            };
        };
        responses: {
            /** @description Refresh run accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshStartResponse"];
                };
            };
            /** @description Refresh already running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRefreshStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current refresh status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshStatusSnapshot"];
                };
            };
        };
    };
    getRefreshSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshSettingsSnapshot"];
                };
            };
        };
    };
    postRefreshSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshSettingsSnapshot"];
            };
        };
        responses: {
            /** @description Updated refresh settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshSettingsSnapshot"];
                };
            };
        };
    };
    postDuplicateScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateScanRequest"];
            };
        };
        responses: {
            /** @description Duplicate scan results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateScanResponse"];
                };
            };
            /** @description Invalid duplicate scan request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postDuplicateApply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateApplyRequest"];
            };
        };
        responses: {
            /** @description Duplicate apply results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateApplyResponse"];
                };
            };
            /** @description Invalid duplicate apply request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postAutoTagScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoTagScanRequest"];
            };
        };
        responses: {
            /** @description Auto-tag scan results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoTagScanResponse"];
                };
            };
            /** @description Invalid auto-tag scan request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postAutoTagApply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoTagApplyRequest"];
            };
        };
        responses: {
            /** @description Auto-tag apply results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoTagApplyResponse"];
                };
            };
            /** @description Invalid auto-tag apply request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postClientLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientLogRequest"];
            };
        };
        responses: {
            /** @description Log accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted: boolean;
                    };
                };
            };
        };
    };
    getThumbnailByItemId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thumbnail image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description Thumbnail not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEventsSse: {
        parameters: {
            query?: {
                /** @description Query-string reconnect revision fallback for browser EventSource clients. */
                lastEventId?: string;
                /** @description Stable client identity for cross-request correlation. */
                clientId?: string | null;
                /** @description Optional runtime session identity for reconnect/playback correlation. */
                sessionId?: string | null;
                /** @description Optional client type hint (for example desktop/web/mobile-web/operator). */
                clientType?: string | null;
                /** @description Optional friendly device/client label shown in operator diagnostics. */
                deviceName?: string | null;
            };
            header?: {
                /** @description Last acknowledged SSE revision from the previous connection. */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream (SSE) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ServerEventEnvelope"];
                };
            };
            /** @description Unauthorized when auth is required and request is not paired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
